### ISSUE TITLE
SignUp Screen

### ISSUE THREAD

**Issue by Blackrush** [rouenssi-tnp/scims#8]
- user account form
  - first name
  - last name
  - e-mail
  - password
- displays data validation errors

**Comment by Blackrush** [comment]
@mathieubrochard are you okay with current form styling ? I was going to abstract it away in their own components

**Comment by mathieubrochard** [comment]
![scims_signup](https://cloud.githubusercontent.com/assets/10001635/20041043/4f8c3914-a463-11e6-9180-3f58d73e583d.png)

**Comment by Blackrush** [comment]
TODO 

- [ ] produce re-usable form styling (needed for #9)
